
package it.polito.dp2.WF.sol4.server.workflow;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.datatype.XMLGregorianCalendar;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * Read-only interface for Processes and WorkFlows
 * 
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WFReader", targetNamespace = "http://www.example.org/Workflow/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WFReader {


    /**
     * Operation for reading (paginated) list of workFlows
     * 
     * @return
     *     returns java.util.List<java.lang.String>
     * @throws ServerErrorFault_Exception
     */
    @WebMethod(action = "http://www.example.org/WFReader/getWorkFlows")
    @WebResult(name = "flowName", targetNamespace = "http://www.example.org/Workflow/")
    @RequestWrapper(localName = "getWorkFlows", targetNamespace = "http://www.example.org/Workflow/", className = "it.polito.dp2.WF.sol4.server.workflow.GetWorkFlows")
    @ResponseWrapper(localName = "getWorkFlowsResponse", targetNamespace = "http://www.example.org/Workflow/", className = "it.polito.dp2.WF.sol4.server.workflow.GetWorkFlowsResponse")
    public List<String> getWorkFlows()
        throws ServerErrorFault_Exception
    ;

    /**
     * Operation for reading (paginated) list of processes
     * 
     * @param flowName
     * @return
     *     returns java.util.List<javax.xml.datatype.XMLGregorianCalendar>
     * @throws ServerErrorFault_Exception
     * @throws WrongArgumentFault
     */
    @WebMethod(action = "http://www.example.org/WFReader/getProcesses")
    @WebResult(name = "startTime", targetNamespace = "http://www.example.org/Workflow/")
    @RequestWrapper(localName = "getProcesses", targetNamespace = "http://www.example.org/Workflow/", className = "it.polito.dp2.WF.sol4.server.workflow.GetProcesses")
    @ResponseWrapper(localName = "getProcessesResponse", targetNamespace = "http://www.example.org/Workflow/", className = "it.polito.dp2.WF.sol4.server.workflow.GetProcessesResponse")
    public List<XMLGregorianCalendar> getProcesses(
        @WebParam(name = "flowName", targetNamespace = "http://www.example.org/Workflow/")
        String flowName)
        throws ServerErrorFault_Exception, WrongArgumentFault
    ;

    /**
     * Operation for reading information about a single workflow
     * 
     * @param flowName
     * @return
     *     returns it.polito.dp2.WF.sol4.server.workflow.WorkflowType
     * @throws ServerErrorFault_Exception
     * @throws WrongArgumentFault
     */
    @WebMethod(action = "http://www.example.org/WFReader/getWorkFlow")
    @WebResult(name = "workflow", targetNamespace = "http://www.example.org/Workflow/")
    @RequestWrapper(localName = "getWorkFlow", targetNamespace = "http://www.example.org/Workflow/", className = "it.polito.dp2.WF.sol4.server.workflow.GetWorkFlow")
    @ResponseWrapper(localName = "getWorkFlowResponse", targetNamespace = "http://www.example.org/Workflow/", className = "it.polito.dp2.WF.sol4.server.workflow.GetWorkFlowResponse")
    public WorkflowType getWorkFlow(
        @WebParam(name = "flowName", targetNamespace = "http://www.example.org/Workflow/")
        String flowName)
        throws ServerErrorFault_Exception, WrongArgumentFault
    ;

    /**
     * Operation for reading information about a single process
     * 
     * @param startTime
     * @param flowName
     * @return
     *     returns it.polito.dp2.WF.sol4.server.workflow.ProcessType
     * @throws ServerErrorFault_Exception
     * @throws WrongArgumentFault
     */
    @WebMethod(action = "http://www.example.org/WFReader/getProcess")
    @WebResult(name = "process", targetNamespace = "http://www.example.org/Workflow/")
    @RequestWrapper(localName = "getProcess", targetNamespace = "http://www.example.org/Workflow/", className = "it.polito.dp2.WF.sol4.server.workflow.GetProcess")
    @ResponseWrapper(localName = "getProcessResponse", targetNamespace = "http://www.example.org/Workflow/", className = "it.polito.dp2.WF.sol4.server.workflow.GetProcessResponse")
    public ProcessType getProcess(
        @WebParam(name = "flowName", targetNamespace = "http://www.example.org/Workflow/")
        String flowName,
        @WebParam(name = "startTime", targetNamespace = "http://www.example.org/Workflow/")
        XMLGregorianCalendar startTime)
        throws ServerErrorFault_Exception, WrongArgumentFault
    ;

}
