
package it.polito.dp2.WF.sol4.client1.workflow;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WFProcessCreator", targetNamespace = "http://www.example.org/Workflow/", wsdlLocation = "file:/C:/Users/Eli/workspace/Assignment4b%20-%20alltestspassed/wsdl/Workflow.wsdl")
public class WFProcessCreator_Service
    extends Service
{

    private final static URL WFPROCESSCREATOR_WSDL_LOCATION;
    private final static WebServiceException WFPROCESSCREATOR_EXCEPTION;
    private final static QName WFPROCESSCREATOR_QNAME = new QName("http://www.example.org/Workflow/", "WFProcessCreator");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Eli/workspace/Assignment4b%20-%20alltestspassed/wsdl/Workflow.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WFPROCESSCREATOR_WSDL_LOCATION = url;
        WFPROCESSCREATOR_EXCEPTION = e;
    }

    public WFProcessCreator_Service() {
        super(__getWsdlLocation(), WFPROCESSCREATOR_QNAME);
    }

    public WFProcessCreator_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WFPROCESSCREATOR_QNAME, features);
    }

    public WFProcessCreator_Service(URL wsdlLocation) {
        super(wsdlLocation, WFPROCESSCREATOR_QNAME);
    }

    public WFProcessCreator_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WFPROCESSCREATOR_QNAME, features);
    }

    public WFProcessCreator_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WFProcessCreator_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WFProcessCreator
     */
    @WebEndpoint(name = "WFProcessCreatorSOAP")
    public WFProcessCreator getWFProcessCreatorSOAP() {
        return super.getPort(new QName("http://www.example.org/Workflow/", "WFProcessCreatorSOAP"), WFProcessCreator.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WFProcessCreator
     */
    @WebEndpoint(name = "WFProcessCreatorSOAP")
    public WFProcessCreator getWFProcessCreatorSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/Workflow/", "WFProcessCreatorSOAP"), WFProcessCreator.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WFPROCESSCREATOR_EXCEPTION!= null) {
            throw WFPROCESSCREATOR_EXCEPTION;
        }
        return WFPROCESSCREATOR_WSDL_LOCATION;
    }

}
