
package it.polito.dp2.WF.sol4.client1.workflow;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "WFReader", targetNamespace = "http://www.example.org/Workflow/", wsdlLocation = "file:/C:/Users/Eli/workspace/Assignment4b%20-%20alltestspassed/wsdl/Workflow.wsdl")
public class WFReader_Service
    extends Service
{

    private final static URL WFREADER_WSDL_LOCATION;
    private final static WebServiceException WFREADER_EXCEPTION;
    private final static QName WFREADER_QNAME = new QName("http://www.example.org/Workflow/", "WFReader");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/Eli/workspace/Assignment4b%20-%20alltestspassed/wsdl/Workflow.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        WFREADER_WSDL_LOCATION = url;
        WFREADER_EXCEPTION = e;
    }

    public WFReader_Service() {
        super(__getWsdlLocation(), WFREADER_QNAME);
    }

    public WFReader_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), WFREADER_QNAME, features);
    }

    public WFReader_Service(URL wsdlLocation) {
        super(wsdlLocation, WFREADER_QNAME);
    }

    public WFReader_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, WFREADER_QNAME, features);
    }

    public WFReader_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public WFReader_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WFReader
     */
    @WebEndpoint(name = "WFReaderSOAP")
    public WFReader getWFReaderSOAP() {
        return super.getPort(new QName("http://www.example.org/Workflow/", "WFReaderSOAP"), WFReader.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WFReader
     */
    @WebEndpoint(name = "WFReaderSOAP")
    public WFReader getWFReaderSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/Workflow/", "WFReaderSOAP"), WFReader.class, features);
    }

    private static URL __getWsdlLocation() {
        if (WFREADER_EXCEPTION!= null) {
            throw WFREADER_EXCEPTION;
        }
        return WFREADER_WSDL_LOCATION;
    }

}
