
package it.polito.dp2.WF.sol4.client1.workflow;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "WrongStartTimeFault", targetNamespace = "http://www.example.org/Workflow/")
public class WrongStartTimeFault_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private WrongStartTimeFault faultInfo;

    /**
     * 
     * @param faultInfo
     * @param message
     */
    public WrongStartTimeFault_Exception(String message, WrongStartTimeFault faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param faultInfo
     * @param cause
     * @param message
     */
    public WrongStartTimeFault_Exception(String message, WrongStartTimeFault faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: it.polito.dp2.WF.sol4.client1.workflow.WrongStartTimeFault
     */
    public WrongStartTimeFault getFaultInfo() {
        return faultInfo;
    }

}
